### ISSUE TITLE
Network: .local und hostname Auflösung

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#11]
Die Hostname-Auflösung funktioniert meistens, aber nicht immer mit dem gleichen Mechanismus und nicht vorhersagbar.

- [x] Micha Informieren
- [x] fix

**Comment by mipreuss** [comment]
ab Montag Triggern

**Comment by bastinat0r** [comment]
systemd-resolved neustarten, 10. ... .33 als nameserver
