### ISSUE TITLE
Flash an SD card

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#13]
Use https://github.com/ovgu-FINken/turtlewriter to flash an SD.
Use 32-bit ubuntu (18.04).

**Comment by maz3max** [comment]
Needed base image is `ubuntu-18.04.3-preinstalled-server-armhf+raspi3.img`.
It has to be renamed or linked to `base.img`, otherwise the script won`t work.

**Comment by maz3max** [comment]
`rsync` is a dependency
