### ISSUE TITLE
Start the Simulation, Control one Robot

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#15]
* start simulation
* you control one robot (teleop) (simulated and real)

**Comment by maz3max** [comment]
On the turtlebot, `netplan` failed.
Quick fix: `sudo mv /etc/netplan/50-cloud-init.yaml ~/`

**Comment by maz3max** [comment]
Running `~/DrivingSwarm/firstrun.sh` seems to be useful.

**Comment by maz3max** [comment]
`export TURTLEBOT3_MODEL=burger` has to be set on every terminal.

**Comment by maz3max** [comment]
Remember to source both `/opt/ros/melodic/setup.bash` and `~/DrivingSwarm/devel/setup.bash`

**Comment by maz3max** [comment]
Environment variables `ROS_MASTER_URI` and `ROS_HOSTNAME` must be set on both the desktop and the robot.
On the robot, `roslaunch turtlebot3_bringup turtlebot3_robot.launch` must be launched.
On the desktop, `roslaunch turtlebot3_bringup turtlebot3_remote.launch` must be launched.
Then, we can run the all the other stuff like rviz and the teleop nodes.

**Comment by maz3max** [comment]
![grafik](https://user-images.githubusercontent.com/9154124/67008850-b3bc8200-f0ea-11e9-96a6-1aae49c729d9.png)

**Comment by maz3max** [comment]
for simulation, following launch files need to be launched separately:
`roslaunch turtlebot3_fake turtlebot3_fake.launch`
`roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch`

**Comment by maz3max** [comment]
our `.bashrc` of the turtlebook:
```
source /opt/ros/melodic/setup.bash
source ~/DrivingSwarm/devel/setup.bash

export ROS_MASTER_URI=http://10.61.7.100:11311
export ROS_HOSTNAME=10.61.7.100
export TURTLEBOT3_MODEL=burger
```
