### ISSUE TITLE
General setup

### ISSUE THREAD

**Issue by treegeist** [ovgu-FINken/DrivingSwarm#2]
- [x] making turtles easily identifiable from outside (coloured labels? / naming scheme)
- [x] rotate raspberry on one bot
- [x] re-install  ubuntu & test wayland on laptop
- [x] setup of ros melodic morenia for all turtlebots
- [x] setup of ros-mm for laptop
- [x] easier .bashrc
- [x] multi-master setup
- [x] controlling node for sending commands to initialise/control swarm behaviour

**Comment by HawkCorrigan** [comment]
Nach ausführen des python scripts und durchlaufen der shellscripts fehlen an paketen um ein catkin make auszuführen:

xacro
urdf
interactive_markers
gcc-7-arm-linux-gnueabihf
g++-7-arm-linux-gnueabihf
ausserdem fehlen die CC und CXX env variablen

ausserdem fehlen an paketen um das standard bringup script zu starten:
rosserial_python

ausserdem funktioniert distcc nur local

ausserdem schmiert der micro installer part des scripts mit syntax fehlern ab

ausserdem funktioniert die wlan konfiguration nicht





nach dem fixen dieser sachen kompiliert zumindest der roboter
funktionieren tut er davon immer noch nicht was wahrscheinlich mit dem nicht gesetzten hostnamen sowie der fast leeren bashrc etc. zusammenhängt

**Comment by treegeist** [comment]
Done
