### ISSUE TITLE
define an interface inkl. meta data

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#23]
- multiple localisations in parallel (n-systems localise m-robots)
- aggregate localisation is possible
- different origins

**Comment by bastinat0r** [comment]
- [x] document your specification

**Comment by maz3max** [comment]
# Proposal for interface
## TF
* `world`: root coordinate system
    * `loc_system<i>`: root coordinate system of particular localisation system
        * `loc_system<i>/target<j>`: target coordinate system

Only publish transformations between adjacent coordinate systems! Mapping from target to robot has to be done separately.

## Additional ROS Topics
* `/loc_system_meta<i>/has_orientation`: int8, values: `0/1`
* `/loc_system_meta<i>/name`: String, values: `Camera/SLAM/ACML/Radio`
* `/loc_system_meta<i>/target<j>/accuracy`:  [PoseWithCovarianceStamped](http://docs.ros.org/api/geometry_msgs/html/msg/PoseWithCovarianceStamped.html) (?)

**Comment by maz3max** [comment]
# Proposal for interface - Update 2
## TF
* `world`: root coordinate system
    * `loc_system_<name>`: root coordinate system of particular localisation system
        * `loc_system_<name>/target<j>`: target coordinate system

Only publish transformations between adjacent coordinate systems! Mapping from target to robot has to be done separately.

## Additional ROS Topics

* `/loc_system_meta_<name>`:  localisation_msgs/localisation_meta

localisation_msgs/localisation_meta consist of
`has_orientation`:  bool
`correct_mapping`: bool
`accuracy`: float64

**Comment by Scyten** [comment]
python snipped:
```python
import rospy
from localisation_msgs.msg import localisation_meta

locSystemName = "fakelocalisation"

rospy.init_node(locSystemName)
topic_metadata = rospy.Publisher('loc_system_meta_' + locSystemName, localisation_meta,  queue_size=1)

localisation_meta_msg = localisation_meta()
localisation_meta_msg.has_orientation = True
localisation_meta_msg.correct_mapping = True
localisation_meta_msg.accuracy = 1

topic_metadata.publish(localisation_meta_msg);
```

**Comment by jbeckhaus** [comment]
DONE (only for documentation reasons still open)

**Comment by Scyten** [comment]
I think if needed, we can look up this in the code or the closed issues.
