### ISSUE TITLE
working multilateration

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#25]

**Comment by bastinat0r** [comment]
based on anchornodes

**Comment by jbeckhaus** [comment]
## get messages via UART: 
* sudo systemctl stop serial-getty@ttyS0.service
* chmod a+rw /dev/ttyS0
* picocom /dev/ttyS0 -b 115200

**Comment by jbeckhaus** [comment]
sudo systemctl mask serial-getty@ttyS0.service 

to permanently deactivate serial blocking service

**Comment by jbeckhaus** [comment]
Filter in range-publisher node einbauen (rosparam für nummer an die gefiltert werden soll)

**Comment by jbeckhaus** [comment]
zuordnungsdiemma ? yaml ?

**Comment by jbeckhaus** [comment]
sender / receiver id aus dem modul heraus nehmen ! (steht in der paparazzi msg drin)

**Comment by jbeckhaus** [comment]
todo: namespace für nodes (launch file) und tf (namen des tf childs = namespace name) !

**Comment by jbeckhaus** [comment]
filter einbauen : 
* nur ranges schicken die absender gleich modul adressen im paparazzi header sind 
  * modul hat addresse 22 --> schreibt in paparazzi msg header seine adresse 
  * modul sendet ranges von 22-->120 und 23-->120 --> nur 22->120 kommt durch

**Comment by jbeckhaus** [comment]
todo: wenn timeout von messages--> aufpassen das die localisierung nicht abstirbt weil sie keine distancen zum berrechnen hat --> exeption einbauen

**Comment by jbeckhaus** [comment]
todo: metadaten

**Comment by jbeckhaus** [comment]
posearray message rausschmeißen

**Comment by jbeckhaus** [comment]
filter dings parametrisieren

**Comment by jbeckhaus** [comment]
zuordnung roboter zu modul-ids

**Comment by jbeckhaus** [comment]
Teambeschluss: zuordnung ModuleID zu Turtlebot statisch in config datei hinterlegt

**Comment by jbeckhaus** [comment]
make bash-script to fix "getty" stuff and launch robot node for id publishing

**Comment by jbeckhaus** [comment]
also auch chown stuff !!! 
auch für turtleboot chown stuff (dokumentieren)

**Comment by jbeckhaus** [comment]
todo: launchfile für turtletransform (mit namespace und so)

**Comment by jbeckhaus** [comment]
CORONA ;(
