### ISSUE TITLE
find a transformation between coordinate sytems

### ISSUE THREAD

**Issue by bastinat0r** [ovgu-FINken/DrivingSwarm#26]
- find transform between coordinate systems/targets
   - Camera + UWB -> SLAM/AMCL
- target mapping

**Comment by Scyten** [comment]
Nico, wrote a Camera and UWB target mapping. (Since the Transformations is static and known, a nearest neighbor approach works very well). 

But we need a learning approach to map AMCL to these two systems.
Input: Rotation, Translation
Minimize: Error

**Comment by Scyten** [comment]
- Translation works
- on rotation we are testing
