### ISSUE TITLE
Localisation Output

### ISSUE THREAD

**Issue by jbeckhaus** [ovgu-FINken/DrivingSwarm#40]
a new Fake-Localization System is used as output
It uses the other localization systems as input and generates an combined output (configurable)

**Comment by Scyten** [comment]
I have created a dummy node that takes the camera system data and publishes tf from world to tb_N. 
This node misses the following (has to be completed)
- Mapping from AMCL to Camera/UWB
- Parameter controlled: How the combined data should be calculated (input value fusion)

**Comment by jbeckhaus** [comment]
done
