### ISSUE TITLE
Implement automatic installation

### ISSUE THREAD

**Issue by treegeist** [ovgu-FINken/DrivingSwarm#5]
- [ ] figure out what has to be installed each time
  - [ ] micro
  - [ ] auto-starting ssh
- [ ] test dd for copying install
- [ ] write script
- [ ] test
- [ ] document for updating script to newer ubuntu / ros -versions

**Comment by Ripsnapper** [comment]
NTP needs to be configured properlly

**Comment by dermalikmann** [comment]
APT-packages:
```
vim 
htop
iftop
git
openssh-server
build-essential
tmux
curl
wget
[distcc](https://rtt-lwr.readthedocs.io/en/latest/adv-tutos/ccache-distcc.html)
ccache
gcc=7.4.0
```

**Comment by bastinat0r** [comment]
`distcc` https://rtt-lwr.readthedocs.io/en/latest/adv-tutos/ccache-distcc.html with configuration
`ccache`
`gcc` (same version as turtlebook)

**Comment by t-aus-m** [comment]
`python-catkin-tools`

**Comment by treegeist** [comment]
Packages for #6 
```
ros-melodic-navigation
```

**Comment by bastinat0r** [comment]
additional package: `gitman`

**Comment by t-aus-m** [comment]
- `python-pip`

**Comment by bastinat0r** [comment]
`scikit-image`

**Comment by t-aus-m** [comment]
Siehe #2 :

> Nach ausführen des python scripts und durchlaufen der shellscripts fehlen an paketen um ein catkin make auszuführen:
> 
> xacro
> urdf
> interactive_markers
> gcc-7-arm-linux-gnueabihf
> g++-7-arm-linux-gnueabihf
> ausserdem fehlen die CC und CXX env variablen
> 
> ausserdem fehlen an paketen um das standard bringup script zu starten:
> rosserial_python
> 
> ausserdem funktioniert distcc nur local
> 
> ausserdem schmiert der micro installer part des scripts mit syntax fehlern ab
> 
> ausserdem funktioniert die wlan konfiguration nicht
> 
> nach dem fixen dieser sachen kompiliert zumindest der roboter
> funktionieren tut er davon immer noch nicht was wahrscheinlich mit dem nicht gesetzten hostnamen sowie der fast leeren bashrc etc. zusammenhängt

Außerdem müssen die seriellen Schnittstellen `ttyACM0` und `ttyAMA0` als ausführbar markiert werden

**Comment by t-aus-m** [comment]
Repo `deb http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu bionic main` fehlt, sowie die Pakete `raspberrypi-sys-mods` und `raspi-config`

**Comment by treegeist** [comment]
Should be done
